### PR TITLE
delete 'routing.cn.md' and update 'route.cn.md'.

### PR DESCRIPTION
**Pull request by wgy8283335**
I've updated 'route.cn.md' and delete 'routing.cn.md'. Please feel free, if you have any suggestion.

### CODE REVIEW

**Comment by wgy8283335** [comment]
@terrymanu ，I've updated 'route.cn.md' and delete 'routing.cn.md'. Please feel free, if you have any suggestion.

**Comment by terrymanu** [comment]
Thank you, I will merge it

**Comment by terrymanu** [comment]
I just revise some doc (91e355c), please check

**Comment by wgy8283335** [comment]
@terrymanu. Thank you for revising the document, especially for modifying syntax.
Do I need to translate the document in English?

**Comment by wgy8283335** [comment]
@terrymanu. Thank you for revising the document, especially for modifying syntax.
Do I need to translate the document in English?

**Pull request merged**
