### PR TITLE
Add routing explanation for #113.

### PR DESCRIPTION
**Pull request by wgy8283335**
I have added routing explanation in 'routing.cn.md' document. Please feel free to let me know if there is something need to be modified.

### CODE REVIEW

**Comment by cherrylzhao** [comment]
nice work!

**Comment by terrymanu** [comment]
Thank you, we will translate to en soon

**Comment by wgy8283335** [comment]
@cherrylzhao. Thank you.

**Comment by wgy8283335** [comment]
@cherrylzhao. For translation, I will start to work from tomorrow.

**Comment by terrymanu** [comment]
Hi, I read the document, it is very similar with https://shardingsphere.apache.org/document/current/cn/features/sharding/principle/route/
Can you update this page instead of create a new page?

**Comment by terrymanu** [comment]
I just revert this merge. Hope you update page [1]

[1] https://shardingsphere.apache.org/document/current/cn/features/sharding/principle/route/

**Comment by terrymanu** [comment]
Another thing I want remind is the document is not a well-format of Hugo.
So I suggest you may use hugo to adjust your page's format before you submit.
about Hugo's info please see our README.md, url is [1]

[1] https://github.com/apache/incubator-shardingsphere-doc/blob/master/README.md

**Comment by wgy8283335** [comment]
@terrymanu, I got it.

**Pull request merged**
