### PR TITLE
add code conduct file shardingsphere-settings.jar 

### PR DESCRIPTION
**Pull request by cheese8**

### CODE REVIEW

**Comment by RaigorJiang** [comment]
@cheese8 
Thank you, but please refer to this PR: https://github.com/apache/shardingsphere-doc/pull/562

**Comment by cheese8** [comment]
ok, but code conduct file still 404, the path should be community/data/shardingsphere-settings.jar but community/shardingsphere-settings.jar @RaigorJiang

**Comment by RaigorJiang** [comment]
@cheese8 
It works now, fixed by https://github.com/apache/shardingsphere-doc/pull/566.
https://shardingsphere.apache.org/community/data/shardingsphere-settings.jar

**Review by tristaZero — APPROVED** [review]

**Comment by tristaZero** [comment]
@cheese8 Hey great job.

**Comment by cheese8** [comment]
thanks

**Pull request merged**
